// Dev-only demo seeding (plan Milestone D demo checkpoint): the real ATK data
// plus two tiny fake books so multi-book tap-order colors are demoable.
// Loaded ONLY via dynamic import from a DEV-guarded button in DevGallery.
//
// Task 25 supersedes the original CSV-based ATK seeding: the ATK index now
// ships as a content pack (public/packs/atk-complete.json, generated by
// tools/build_pack.py), so dev seeding installs it through installPack() —
// the exact code path users hit from the Library (the dev server serves
// public/). The `?raw` CSV import is gone with it; nothing from background/
// can reach production bundles anymore.
//
// Idempotent by design: installPack no-ops when the pack's book exists; the
// fake books are guarded by book name.
import { store } from '../data/store';
import { newId } from '../data/types';
import type { MadeEntry, Recipe } from '../data/types';
import { installPack } from '../data/packs';

// Owner-confirmed at Checkpoint 1 (plan "Checkpoint 1 amendments" item 2):
// exact ATK edition title, en dash in the year range. The pack ships under
// this same name (build_pack.py --name).
export const ATK_BOOK_NAME = "The Complete America's Test Kitchen TV Show Cookbook 2001–2025";

export async function seedAtk(): Promise<string> {
  const already = store.books.find((b) => b.packId === 'atk-complete');
  if (already) return `${already.name}: already installed`;
  const { book, recipes } = await installPack('atk-complete');
  return `${book.name}: +${recipes.length} recipes (via installPack)`;
}

// name, page, category, tags, madeDates (each date ⇒ one MadeEntry)
type FakeRow = [string, string, string, string[], string[]?];
const FAKE_BOOKS: { name: string; rows: FakeRow[] }[] = [
  {
    name: 'Weeknight Standbys',
    rows: [
      ['Skillet Chicken Thighs', '12', 'Mains', ['chicken'], ['2026-06-02', '2026-07-01']],
      ['Garlic Butter Salmon', '18', 'Mains', ['fish']],
      ['Sheet-Pan Sausage and Peppers', '24', 'Mains', ['pork']],
      ['Crispy Fried Chicken Cutlets', '15', 'Mains', ['chicken', 'fried']],
      ['Smashed Potatoes', '41', 'Sides', ['potato'], ['2026-05-20']],
      ['Charred Broccoli', '44', 'Sides', ['vegetable']],
      ['Tomato Soup with Grilled Cheese', '52', 'Soups & Stews', ['creamy']],
      ['Chopped Kale Salad', '60', 'Salads', ['green']],
      ['One-Bowl Brownies', '71', 'Desserts', ['chocolate']],
      ['Lemon Yogurt Cake', '75', 'Desserts', ['cake'], ['2026-06-15']],
    ],
  },
  {
    name: 'Sunday Baking',
    rows: [
      ['Overnight Sourdough Loaf', '8', 'Breads', ['yeasted']],
      ['Buttermilk Biscuits', '14', 'Breads', ['quick'], ['2026-06-08']],
      ['Cinnamon Swirl Rolls', '21', 'Breads', ['yeasted']],
      ['Chocolate Chip Cookies', '33', 'Desserts', ['cookie', 'chocolate'], ['2026-04-12', '2026-06-28']],
      ['Peach Galette', '39', 'Desserts', ['fruit', 'pie']],
      ['Vanilla Bean Pound Cake', '45', 'Desserts', ['cake']],
      ['Dutch Baby Pancake', '55', 'Breakfast & Brunch', ['pancake']],
      ['Blueberry Muffins', '58', 'Breakfast & Brunch', ['muffin']],
    ],
  },
];

export async function seedDemoBooks(): Promise<string> {
  const results: string[] = [];
  for (const fake of FAKE_BOOKS) {
    if (store.books.some((b) => b.name === fake.name)) {
      results.push(`${fake.name}: already seeded`);
      continue;
    }
    const bookId = newId();
    await store.addBook({ id: bookId, name: fake.name, tags: [], archived: false, createdAt: new Date().toISOString() });
    const recipes: Recipe[] = fake.rows.map(([name, page, category, tags]) => ({
      id: newId(),
      bookId,
      name,
      page,
      category,
      tags,
      status: 'active',
      isCustom: false,
      attachmentIds: [],
      createdAt: new Date().toISOString(),
    }));
    await store.addRecipes(recipes);
    const entries: MadeEntry[] = fake.rows.flatMap(([name, , , , dates], i) =>
      (dates ?? []).map((date) => ({
        id: newId(),
        recipeId: recipes[i].id,
        date,
        rating: 8,
        notes: `Seed entry for ${name}`,
        photoIds: [],
      })),
    );
    for (const e of entries) await store.addMadeEntry(e);
    results.push(`${fake.name}: +${recipes.length} recipes, ${entries.length} made entries`);
  }
  return results.join(' · ');
}
