// Content packs (plan Task 25): catalog fetch + install/update/uninstall.
// Packs are static JSON under public/packs/ (generated by tools/build_pack.py
// — their categories are ALREADY the app's 11 defaults, so planImport maps
// them cleanly). Installing creates a normal Cookbook tagged with
// packId/packVersion; from then on it behaves like any other book.
import { newId } from './types';
import type { Cookbook, PageStatus, Recipe } from './types';
import { UNCATEGORIZED } from './categories';
import { planImport } from '../logic/importer';
import { store } from './store';

export interface CatalogPack {
  id: string;
  title: string;
  author?: string;
  year?: number;
  country?: string;
  cuisines: string[];
  era?: string;
  /** 'index-only' = names+pages, own the book; 'linked' = readable online. */
  type: 'index-only' | 'linked';
  recipeCount: number;
  categories?: string[];
  /** Path relative to BASE_URL, e.g. "packs/atk-complete.json". */
  file: string;
  version: number;
}

interface PackRecipe {
  name: string;
  page: string;
  category?: string;
  tags: string[];
  link?: { url: string; pageStatus: PageStatus };
}

interface PackFile {
  id: string;
  version: number;
  book: { name: string; tags: string[] };
  recipes: PackRecipe[];
}

export interface Catalog {
  packs: CatalogPack[];
  /** True when the network failed AND no cached copy existed — the Library
   *  shows an offline note instead of an empty catalog. */
  offline: boolean;
}

const SS_KEY = 'p2p:catalog';
let memo: CatalogPack[] | null = null;

/**
 * Module memo → sessionStorage → network. A failed fetch is NOT memoized, so
 * a later call (e.g. reopening the Books tab once back online) retries.
 */
export async function fetchCatalog(): Promise<Catalog> {
  if (memo) return { packs: memo, offline: false };
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}packs/catalog.json`);
    if (!res.ok) throw new Error(`catalog HTTP ${res.status}`);
    const data = (await res.json()) as { packs: CatalogPack[] };
    memo = data.packs;
    try {
      sessionStorage.setItem(SS_KEY, JSON.stringify(data.packs));
    } catch {
      /* quota / private mode — the module memo suffices for this session */
    }
    return { packs: memo, offline: false };
  } catch {
    try {
      const raw = sessionStorage.getItem(SS_KEY);
      if (raw) {
        memo = JSON.parse(raw) as CatalogPack[];
        return { packs: memo, offline: false };
      }
    } catch {
      /* fall through to offline */
    }
    return { packs: [], offline: true };
  }
}

async function fetchPackFile(entry: CatalogPack): Promise<PackFile> {
  const res = await fetch(`${import.meta.env.BASE_URL}${entry.file}`);
  if (!res.ok) throw new Error(`pack ${entry.id} HTTP ${res.status}`);
  return (await res.json()) as PackFile;
}

const catalogEntry = async (id: string): Promise<CatalogPack> => {
  const { packs } = await fetchCatalog();
  const entry = packs.find((p) => p.id === id);
  if (!entry) throw new Error(`unknown pack ${id}`);
  return entry;
};

/**
 * Round-2 book metadata derived from a catalog entry. `infoUrl` is set only
 * for LINKED packs — our linked-pack ids ARE archive.org identifiers, so the
 * book links to its free scan; index-only packs (you own the physical book)
 * get no infoUrl and fall back to a "Find this book" web search (bookLink.ts).
 * `cuisines` is always an array (possibly empty) so a populated-but-empty book
 * is distinguishable from one never touched by backfill.
 */
export function catalogMetadata(entry: CatalogPack): Pick<Cookbook, 'author' | 'year' | 'cuisines' | 'infoUrl'> {
  return {
    author: entry.author,
    year: entry.year,
    cuisines: [...entry.cuisines],
    infoUrl: entry.type === 'linked' ? `https://archive.org/details/${entry.id}` : undefined,
  };
}

/**
 * Best-effort backfill for pack books installed BEFORE this metadata existed
 * (the user's already-installed ATK, etc.): for each pack book missing a
 * field, fill it from the catalog entry. Pure + null-tolerant — an empty
 * `packs` (offline / absent catalog) yields no patches, so the caller no-ops
 * and nothing crashes. Only genuinely-absent fields are patched (`=== undefined`),
 * so a user who cleared cuisines by hand is never overwritten.
 */
export function backfillPatches(
  books: Cookbook[],
  packs: CatalogPack[],
): { id: string; patch: Partial<Cookbook> }[] {
  const byId = new Map(packs.map((p) => [p.id, p]));
  const out: { id: string; patch: Partial<Cookbook> }[] = [];
  for (const b of books) {
    if (!b.packId) continue; // user books keep undefined metadata
    const entry = byId.get(b.packId);
    if (!entry) continue; // pack no longer in the catalog — leave it be
    const meta = catalogMetadata(entry);
    const patch: Partial<Cookbook> = {};
    if (b.author === undefined && meta.author !== undefined) patch.author = meta.author;
    if (b.year === undefined && meta.year !== undefined) patch.year = meta.year;
    if (b.cuisines === undefined) patch.cuisines = meta.cuisines;
    if (b.infoUrl === undefined && meta.infoUrl !== undefined) patch.infoUrl = meta.infoUrl;
    if (Object.keys(patch).length > 0) out.push({ id: b.id, patch });
  }
  return out;
}

/**
 * Install: fetch pack file → create the book (packId/packVersion, pack tags)
 * → import recipes through the same planImport pipeline as CSV import.
 * Returns the new book + recipes; the CALLER runs the re-association hook
 * (screens/books/reassociate.tsx) because the prompt is UI.
 */
export async function installPack(id: string): Promise<{ book: Cookbook; recipes: Recipe[] }> {
  const entry = await catalogEntry(id);
  const existing = store.books.find((b) => b.packId === id);
  if (existing) {
    return { book: existing, recipes: store.recipes.filter((r) => r.bookId === existing.id) };
  }
  const pack = await fetchPackFile(entry);
  const book: Cookbook = {
    id: newId(),
    name: pack.book.name,
    tags: [...pack.book.tags],
    archived: false,
    packId: pack.id,
    packVersion: pack.version,
    createdAt: new Date().toISOString(),
    ...catalogMetadata(entry),
  };
  await store.addBook(book);
  const plan = planImport(pack.recipes, [], store.categories.map((c) => c.name));
  // plan.rows is index-aligned with pack.recipes (planImport maps 1:1), which
  // lets the linked-pack `link` slot ride along untouched.
  const recipes: Recipe[] = plan.rows
    .map((row, i) => ({ row, link: pack.recipes[i].link }))
    .filter(({ row }) => row.action === 'add')
    .map(({ row, link }) => ({
      id: newId(),
      bookId: book.id,
      name: row.name,
      page: row.page,
      category: row.category ?? UNCATEGORIZED, // pack categories are pre-mapped; belt-and-braces
      tags: row.tags,
      status: 'active' as const,
      isCustom: false,
      attachmentIds: [],
      link,
      createdAt: new Date().toISOString(),
    }));
  await store.addRecipes(recipes);
  return { book, recipes };
}

/**
 * Non-destructive update to a newer pack version: new recipes are added,
 * changed ones corrected (page/category/link; tags merged as a UNION so user
 * tags survive). It never touches MadeEntries or a recipe's status, and
 * removed rows are left in place — deleting user-visible data is not an
 * update's job.
 */
export async function updatePack(id: string): Promise<{ added: number; updated: number }> {
  const book = store.books.find((b) => b.packId === id);
  if (!book) throw new Error(`pack ${id} is not installed`);
  const entry = await catalogEntry(id);
  if ((book.packVersion ?? 0) >= entry.version) return { added: 0, updated: 0 };
  const pack = await fetchPackFile(entry);
  const existing = store.recipes.filter((r) => r.bookId === book.id);
  const plan = planImport(pack.recipes, existing, store.categories.map((c) => c.name));

  const adds: Recipe[] = plan.rows
    .map((row, i) => ({ row, link: pack.recipes[i].link }))
    .filter(({ row }) => row.action === 'add')
    .map(({ row, link }) => ({
      id: newId(),
      bookId: book.id,
      name: row.name,
      page: row.page,
      category: row.category ?? UNCATEGORIZED,
      tags: row.tags,
      status: 'active' as const,
      isCustom: false,
      attachmentIds: [],
      link,
      createdAt: new Date().toISOString(),
    }));
  if (adds.length > 0) await store.addRecipes(adds);

  let updated = 0;
  for (const [i, row] of plan.rows.entries()) {
    if (row.action !== 'update' || !row.existingId) continue;
    const cur = store.recipes.find((r) => r.id === row.existingId);
    if (!cur) continue;
    await store.updateRecipe(cur.id, {
      page: row.page,
      category: row.category ?? cur.category,
      tags: [...new Set([...cur.tags, ...row.tags])], // union — user tags kept
      link: pack.recipes[i].link ?? cur.link,
      // status deliberately untouched; MadeEntries never touched
    });
    updated += 1;
  }
  await store.updateBook(book.id, { packVersion: pack.version });
  return { added: adds.length, updated };
}

/**
 * Uninstall follows the book rules (spec rule 8): cooking history exists →
 * archive the book (history stays browsable, pack can be re-enabled); no
 * history → hard delete, nothing worth keeping.
 */
export async function uninstallPack(id: string): Promise<'archived' | 'deleted'> {
  const book = store.books.find((b) => b.packId === id);
  if (!book) throw new Error(`pack ${id} is not installed`);
  const recipeIds = new Set(store.recipes.filter((r) => r.bookId === book.id).map((r) => r.id));
  const hasHistory = store.madeEntries.some((m) => m.recipeId !== null && recipeIds.has(m.recipeId));
  if (hasHistory) {
    await store.updateBook(book.id, { archived: true });
    return 'archived';
  }
  await store.deleteBookHard(book.id);
  return 'deleted';
}

// DEV-only escape hatch (same pattern as window.__store in App.tsx): lets
// Playwright/manual console runs exercise update/uninstall, which have no UI
// surface until the settings screens (Task 26+). Compile-time false in prod.
if (import.meta.env.DEV && typeof window !== 'undefined') {
  (window as unknown as { __packs?: object }).__packs = { fetchCatalog, installPack, updatePack, uninstallPack };
}
